#page title
page_title                                : jzvc, sigurni bitcoin novčanik za štednju i plaćanje                     # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : bs                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://jzvc.ba                           # Enter Google Play Store URL.
presskit_download_link                    : https://jzvc.ba                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : jzvc bitcoin novčanik                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : slobodan novac za slobodan narod          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : sigurni bitcoin novčanik za štednju i plaćanje

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : jzvc.ba                                
your_link                                 : https://jzvc.ba                     
your_city                                 : Sarajevo                                
email_address                             : jzvc@jzvc.ba
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Prvi i jedini
    description                           : jzvc je prvi i jedini bitcoin novčanik licenciran od strane Ministarstva finansija uz podršku Lightning Network (prijava u toku).
    fontawesome_icon_name                 : star

  - title                                 : Lako i jednostavno
    description                           : Aktivirajte svoj novčanik za nekoliko sekundi da biste slali ili primali bitcoin.
    fontawesome_icon_name                 : rocket

  - title                                 : 0% naknada
    description                           : Nema naknada za slanje ili primanje sredstava među jzvc korisnicima. Ostali Lightning Network transferi koštaju u prosjeku 0.2%.
    fontawesome_icon_name                 : percent

  - title                                 : Brzinom svjetlosti
    description                           : jzvc je izgrađen na Lightning Networku za trenutne bitcoin transfere.
    fontawesome_icon_name                 : bolt

  - title                                 : Otvoreno 24/7
    description                           : Bitcoin ne prestaje s radom, za razliku od vaše banke.
    fontawesome_icon_name                 : university
    
  - title                                 : Sigurno i bezbjedno
    description                           : Osigurano korištenjem vodećih standarda šifriranja i sigurnosti.
    fontawesome_icon_name                 : lock

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.8
topbar_title_color                        : "#ffffff"

cover_image                               : assets/logo-cropped.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#fe9843"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#666666"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#fe9843"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#fe9843"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
